CREATE PROCEDURE [dbo].[InsertLogSaveGame]
    @ID_GAME INT OUT,
    @DATE DATETIME,
    @COMMENT VARCHAR(50)

AS
    INSERT INTO LOG_GAMES (DATE, COMMENT)
    VALUES (@DATE, @COMMENT)   
    SET @ID_GAME=SCOPE_IDENTITY()
	SELECT SCOPE_IDENTITY()
GO